version: 2
jobs:
  build:

    working_directory: ~/ecoins-rest-service

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: ecoins-rest-service-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: ecoins-rest-service-{{ checksum "pom.xml" }}

      - run: mvn clean package

      - store_artifacts:
          path: target/ecoins-rest-service-0.1-SNAPSHOT.jar